### ISSUE TITLE
Use of `hiredis`

### ISSUE THREAD

**Issue by apalsapure** [silverbucket/node-redis-connection-pool#19]
In the package.json you have included `hiredis` as dependency. But you haven't used it anywhere. Will you remove it? On windows machine, `hiredis` requires lots of things to build. Thanks.

**Comment by silverbucket** [comment]
@apalsapure good point, I seem to remember that hiredis improved performance (the redis package would use hiredis for some operations if it was installed, but wasn't a hard dependency) which is why it's there. But now, reading the node_redis README.md, I don't see that anywhere.

I agree it's a rather heavy dependency and some systems have trouble with the build, so I'll remove it for now, and if I find some more info on it later I'll bring it up again.

**Comment by silverbucket** [comment]
just published `1.6.1`

**Comment by apalsapure** [comment]
Thanks.
